"""empty message

Revision ID: c29b0d9b3aec
Revises: ab21a2f0f02a
Create Date: 2024-10-25 20:13:43.563197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29b0d9b3aec'
down_revision = 'ab21a2f0f02a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('fav', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
